# Site Info
title: Daniel Chen
tagline: 'Perpetually Under Construction'
description: 'A Jekyll theme adapted from <a href="http://lanyon.getpoole.com/" target="_blank">Lanyon</a>. Made by <a href="http://codinfox.github.io" target="_blank">@codinfox</a>.'
#baseurl: ""
url: http://chendaniely.github.io
logo: '/public/dc/dc-69.png'

# Site configurations
gems:
  - jekyll-paginate
  - jekyll-feed
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss
paginate: 10
paginate_path: '/blog/page:num'
permalink: pretty

collections:
  data_science:
    output: true

jupyter_notebooks: /notebooks/

version: 1.0.0

# About/contact
author:
  name: chendaniely
  description: Using computational methods and network science in <strong>public health, epidemiology, psychology, and medicine</strong>.
  gravatar: bafc04ef618c2c9d8d71fac8448bb8c7 # md5 hash of your email address
  contact:
    linkedin:  https://www.linkedin.com/in/danielychen
    github:    https://github.com/chendaniely
    # facebook:  <hide>
    twitter:   https://twitter.com/chendaniely
    instagram: https://www.instagram.com/maveri2k
    lastfm: http://www.last.fm/user/Maveri2k
    # weibo:     http://weibo.com/41173780
    # email:     http://www.google.com/recaptcha/mailhide/d?k=01I3lZFiZYng9N3QxYEtsDaQ==&c=31wAnZkuKqcG0ATAqJN8Z3ln5kkYLA9TwkGc-IbygpM=
    orcid:     http://orcid.org/0000-0003-3857-1741

# Navigation (2nd level links supported)
nav:
  Home:
    - '/'
  Blog:
    - '/blog/'
    - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }
  About:
    - '/about/'
  Projects:
    - /projects/
  Talks:
    - /talks/
  Research:
    - /research/
#   Teaching:
#     - '/teaching/'
#   Data Science:
#     - /data_science/

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image: http://imgs.xkcd.com/comics/frequentists_vs_bayesians.png
  caption: Original Artwork &copy; <a href="https://xkcd.com/1132/">XKCD - Randall Munroe</a>

project_logos:
  safari_books_online: /public/project_images/safari-logo-lockup-sunshine.png
  datacamp: /public/project_images/datacamp_white_fulllogo_tagline.png
  pandas_for_everyone: /public/project_images/pandas_for_everyone.jpg
  github_octocat: /public/project_images/octocat/Octocat.png

podcasts:
- name: Not So Standard Deviations
  image: /public/podcasts/not_so_standard_deviations-500x500.jpg
  url: https://soundcloud.com/nssd-podcast
- name: Partially Derivative
  image: /public/podcasts/partially_derivative-1400x1400.png
  url: http://partiallyderivative.com/
- name: Linear Digressions
  image: /public/podcasts/linear_digressions-630x630.jpg
  url: http://lineardigressions.com/
- name: Data Skeptic
  image: /public/podcasts/data_skeptic-3000x3000.jpg
  url: https://dataskeptic.com/
- name: Becoming a Data Scientist
  image: /public/podcasts/becoming_a_data_scientist.jpg
  url: https://www.becomingadatascientist.com/category/podcast/
- name: Talk Python to Me
  image: /public/podcasts/talk_python_to_me_1400x1400.png
  url: https://talkpython.fm/

- name: Linux Action Show
  image: /public/podcasts/linux_action_show-200x199.png
  url: http://www.jupiterbroadcasting.com/tag/linux-action-show/

- name: Linux Unplugged
  image: /public/podcasts/linux_unplugged-1400x1400.jpg
  url: http://www.jupiterbroadcasting.com/show/linuxun/

- name: Coder Radio
  image: /public/podcasts/coder_radio-630x630.jpg
  url: http://www.jupiterbroadcasting.com/show/coderradio/

- name: Freakonomics
  image: /public/podcasts/freakonomics_radio-1400x1400.png
  url: http://freakonomics.com/

- name: Startalk
  image: /public/podcasts/startalk-1400x1400.jpg
  url: https://www.startalkhttp://127.0.0.1:4000/about/radio.net/category/startalk-radio/

- name: Sawbones
  image: /public/podcasts/sawbones-2400x2400.png
  url: http://www.maximumfun.org/shows/sawbones

- name: The Hilarious World of Depression
  image: /public/podcasts/hilarous-world-depression-576x576.jpg
  url: https://www.apmpodcasts.org/thwod/

- name: Tell Me Something I should Know
  image: /public/podcasts/tell_me_something_i_should_know-550x550.jpg
  url: http://tmsidk.com/

- name: The Daily
  image: /public/podcasts/the_daily.jpg
  url: https://www.nytimes.com/column/the-daily

podcast_settings:
  global_size_width: 100px
  global_size_height: 100px

# Puglins
mathjax: true # whether support mathjax
google_analytics_token: 'UA-54964509-2' # leave blank if you don't want google analytics
disqus_short_name: 'chendaniely' # leave blank if you don't want disqus
